//! All error types for this program

use num_derive::FromPrimitive;
use solana_program::{decode_error::DecodeError, program_error::ProgramError};
use thiserror::Error;

/// Errors that may be returned by the TroveManager program.
#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum TroveManagerError {
    // 0.
    /// The account cannot be initialized because it is already being used.
    #[error("AlreadyInUse")]
    AlreadyInUse,
    /// The program address provided doesn't match the value generated by the program.
    #[error("InvalidProgramAddress")]
    InvalidProgramAddress,
    /// The trove manager state is invalid.
    #[error("InvalidState")]
    InvalidState,
    /// account's owner is invalid.
    #[error("InvalidOwner")]
    InvalidOwner,
    /// invalid borrower operations.
    #[error("InvalidBorrwerOperations")]
    InvalidBorrwerOperations,
    /// borrower trove is not active yet
    #[error("TroveNotActive")]
    TroveNotActive,
    /// Oracle config is invalid
    #[error("Input oracle config is invalid")]
    InvalidOracleConfig,
    /// Invalid account input
    #[error("Invalid account input")]
    InvalidAccountInput,
    /// Math operation overflow
    #[error("Math operation overflow")]
    MathOverflow,
}
impl From<TroveManagerError> for ProgramError {
    fn from(e: TroveManagerError) -> Self {
        ProgramError::Custom(e as u32)
    }
}
impl<T> DecodeError<T> for TroveManagerError {
    fn type_of() -> &'static str {
        "Trove Manager Error"
    }
} 