//! All error types for this program

use num_derive::FromPrimitive;
use solana_program::{decode_error::DecodeError, program_error::ProgramError};
use thiserror::Error;

/// Errors that may be returned by the StabilityPool program.
#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum StabilityPoolError {
    // 0.
    /// The account cannot be initialized because it is already being used.
    #[error("AlreadyInUse")]
    AlreadyInUse,
    /// The program address provided doesn't match the value generated by the program.
    #[error("InvalidProgramAddress")]
    InvalidProgramAddress,
    /// The stability pool state is invalid.
    #[error("InvalidState")]
    InvalidState,
    /// pool token account's owner is invalid.
    #[error("InvalidOwner")]
    InvalidOwner,
    /// given pool token account isn't same with pool token account
    #[error("InvalidPoolToken")]
    InvalidPoolToken,
    /// given frontend wasn't registered
    #[error("NotRegistered")]
    NotRegistered,
    /// given frontend was registered already
    #[error("AlreadyRegistered")]
    AlreadyRegistered,
    /// given user has deposit balance, but it requires no deposit
    #[error("HasDeposit")]
    HasDeposit,
    /// given kickback rate is invalid
    #[error("InvalidKickbackRate")]
    InvalidKickbackRate,
}
impl From<StabilityPoolError> for ProgramError {
    fn from(e: StabilityPoolError) -> Self {
        ProgramError::Custom(e as u32)
    }
}
impl<T> DecodeError<T> for StabilityPoolError {
    fn type_of() -> &'static str {
        "Stability Pool Error"
    }
} 